snussum/api/urls.py
from django.conf.urls import patterns, url

from api.views.update_profile import UpdateProfileUniversity, UpdateProfileNickname,\
    UpdateProfileIntroduce, UpdateProfileGender, ResetPassword, UpdateProfileConditions
from api.views.messages import APIMessageSMS, APIMessageEmail, ContactAdmin
from api.views.messages import APIMessageSMS, APIMessageEmail
from api.views.datings import DatingComment
from api.views.verify import VerifySNUSnulifeLogin, VerifySNUMysnuLogin, VerifySNUMysnuEmail


urlpatterns = patterns(
    '',

    url(r'^login/$', 'rest_framework_jwt.views.verify_jwt_token'),
    url(r'^users/university/$', UpdateProfileUniversity.as_view(), name='update-university'),
    url(r'^users/nickname/$', UpdateProfileNickname.as_view(), name='update-nickname'),
    url(r'^users/introduce/$', UpdateProfileIntroduce.as_view(), name='update-introduce'),
    url(r'^users/gender/$', UpdateProfileGender.as_view(), name='update-gender'),
    url(r'^users/conditions/$', UpdateProfileConditions.as_view(), name='update-conditions'),

    url(r'^users/password/reset/$', ResetPassword.as_view(), name='reset-password'),

    url(r'^ssum/(?P<hash_id>\w+)/comment/$', DatingComment.as_view(), name='dating-comment'),

    url(r'^sms/$', APIMessageSMS.as_view(), name='sms'),
    url(r'^email/$', APIMessageEmail.as_view(), name='email'),

    # SNU Verifications
    url(r'^users/snulife/login/$', VerifySNUSnulifeLogin.as_view(), name='snulife-login'),
    url(r'^users/mysnu/login/$', VerifySNUMysnuLogin.as_view(), name='mysnu-login'),
    url(r'^users/mysnu/email/$', VerifySNUMysnuEmail.as_view(), name='mysnu-email'),

    url(r'^contact/$', ContactAdmin.as_view(), name='contact'),
)

snussum/snussum/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from snussum.views import Home, Dashboard, About, Browser
from snussum.views.rules import Privacy, Service

from relationships.views.dating import DatingList, DatingDetail, DatingAccept, DatingRefuse, DatingRatingCreate
from relationships.views.self_dating import SelfDatingCreate, SelfDatingDetail, \
    SelfDatingApplyCreate, SelfDatingApplyAccept, SelfDatingApplyRefuse, \
    SelfDatingList

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from snussum.sitemaps import sitemaps


urlpatterns = [
    # Django Default
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^%s/' % settings.ADMIN_URL, include(admin.site.urls)),

    url(r'^robots\.txt$', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # Project Libraries
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^summernote/', include('django_summernote.urls')),

    # Project Urls
    url(r'^$', Home.as_view(), name='home'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^browsers/$', Browser.as_view(), name='browsers'),

    url(r'^rules/service/$', Service.as_view(), name='rule-service'),
    url(r'^rules/privacy/$', Privacy.as_view(), name='rule-privacy'),

    url(r'^today/$', Dashboard.as_view(), name='dashboard'),

    url(r'^ssum/$', DatingList.as_view(), name='dating-list'),
    url(r'^ssum/(?P<slug>\w+)/$', DatingDetail.as_view(), name='dating-detail'),
    url(r'^ssum/(?P<slug>\w+)/accept/$', DatingAccept.as_view(), name='dating-accept'),
    url(r'^ssum/(?P<slug>\w+)/refuse/$', DatingRefuse.as_view(), name='dating-refuse'),
    url(r'^ssum/(?P<slug>\w+)/rating/$', DatingRatingCreate.as_view(), name='dating-rating'),

    url(r'^wanted/$', SelfDatingList.as_view(), name='self-dating-list'),
    url(r'^wanted/new/$', SelfDatingCreate.as_view(), name='self-dating-new'),
    url(r'^wanted/(?P<slug>\w+)/$', SelfDatingDetail.as_view(), name='self-dating-detail'),
    url(r'^wanted/(?P<slug>\w+)/apply/$', SelfDatingApplyCreate.as_view(), name='self-dating-apply'),

    url(r'^wanted/(?P<slug>\w+)/apply/(?P<self_dating_apply_hash_id>\w+)/accept/$',
        SelfDatingApplyAccept.as_view(),
        name='self-dating-apply-accept'),
    url(r'^wanted/(?P<slug>\w+)/apply/(?P<self_dating_apply_hash_id>\w+)/refuse/$',
        SelfDatingApplyRefuse.as_view(),
        name='self-dating-apply-refuse'),

    url(r'^', include('users.urls', namespace='users')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^snusex/', include('snusex.urls', namespace='snusex')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

snussum/users/urls.py
from django.conf.urls import patterns, url

from users.views.verify import VerifyUniversity, VerifyUniversitySNU, VerifyProfile
from users.views.profile import Profile, Notification, UpdateUserProfileInformation, UpdateUserProfileAccountEmail, \
    UpdateUserProfileAccountPhonenumber, UpdateUserProfileCondition, UpdateUserProfileImage
from users.views.auth import PasswordReset


urlpatterns = patterns(
    '',

    url(r'^login/$', 'users.views.auth.login', name='login'),
    url(r'^signup/$', 'users.views.auth.signup', name='signup'),
    url(r'^logout/$', 'users.views.auth.logout', name='logout'),

    url(r'^password/reset/$', PasswordReset.as_view(), name='password-reset'),

    url(r'^profile/$', Profile.as_view(), name='profile'),
    url(r'^notifications/$', Notification.as_view(), name='notification'),

    # Update UserProfile
    url(r'^profile/information/$', UpdateUserProfileInformation.as_view(), name='update-profile-information'),
    url(r'^profile/image/$', UpdateUserProfileImage.as_view(), name='update-profile-image'),
    url(r'^profile/account/email/$', UpdateUserProfileAccountEmail.as_view(), name='update-profile-account-email'),
    url(r'^profile/account/phonenumber/$',
        UpdateUserProfileAccountPhonenumber.as_view(),
        name='update-profile-account-phonenumber'),
    url(r'^profile/condition/$', UpdateUserProfileCondition.as_view(), name='update-profile-condition'),

    url(r'^verify/univ/$', VerifyUniversity.as_view(), name='verify-univ'),
    url(r'^verify/snu/$', VerifyUniversitySNU.as_view(), name='verify-snu'),
    url(r'^verify/profile/$', VerifyProfile.as_view(), name='verify-profile'),

    url(r'^verify/university/(?P<university_verification_token>\w+)/$',
        'users.views.verify.university_verification',
        name='university-verification'
        ),
    url(r'^verify/phonenumber/(?P<phonenumber_verification_token>\w+)/$',
        'users.views.verify.phonenumber_verification',
        name='phonenumber-verification'
        ),
)

snussum/users/models/university.py
from django.db import models


class University(models.Model):
    full_name = models.CharField(max_length=16, blank=True, null=True, unique=True)
    short_name = models.CharField(max_length=8, blank=True, null=True, unique=True)

    email = models.CharField(max_length=16, blank=True, null=True, unique=True)
    slug = models.CharField(max_length=8, blank=True, null=True, unique=True)

    def __str__(self):
        return self.full_name

snussum/users/forms/profile.py
from django.forms import ModelForm

from django.contrib.auth.models import User
from users.models.user_profile import UserProfile

from django_summernote.widgets import SummernoteInplaceWidget


class UserProfileVerificationForm(ModelForm):

    class Meta:
        model = UserProfile
        fields = [
            # Required Fields
            'nickname',
            'is_boy',
            'profile_introduce',

            # Optional Fields
            'age',
            'height',
        ]
        widgets = {
            'profile_introduce': SummernoteInplaceWidget(),
        }


class UserProfileInformationForm(ModelForm):

    class Meta:
        model = UserProfile
        fields = [
            'nickname',
            'profile_introduce',
            'age',
            'height',
            'region',
        ]
        widgets = {
            'profile_introduce': SummernoteInplaceWidget(),
        }


class UserProfileImageForm(ModelForm):

    class Meta:
        model = UserProfile
        fields = ['profile_image', ]


class UserProfileAccountPhonenumberForm(ModelForm):

    class Meta:
        model = UserProfile
        fields = ['phonenumber']


class UserProfileAccountEmailForm(ModelForm):

    class Meta:
        model = User
        fields = ['email']

snussum/api/views/verify.py
from rest_framework.views import APIView

from rest_framework.permissions import IsAuthenticated

from rest_framework.response import Response
from rest_framework import status

from django.contrib.auth.models import User
from users.models.university import University

from users.tasks.verification import snulife_login, mysnu_login


class VerifySNUBase(APIView):
    permission_classes = (IsAuthenticated, )


class VerifySNUSnulifeLogin(VerifySNUBase):

    def post(self, request, *args, **kwargs):
        username = request.data.get('username', None)
        password = request.data.get('password', None)

        result = snulife_login(username, password)
        if result:
            university = University.objects.get(slug="snu")
            self.request.user.userprofile.university = university
            self.request.user.userprofile.is_university_verified = True
            self.request.user.userprofile.snulife_username = username
            self.request.user.userprofile.save()
            return Response(status=status.HTTP_200_OK)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)


class VerifySNUMysnuLogin(VerifySNUBase):

    def post(self, request, *args, **kwargs):
        username = request.data.get('username', None)
        password = request.data.get('password', None)

        result = mysnu_login(username, password)
        if result:
            university = University.objects.get(slug="snu")
            self.request.user.userprofile.university = university
            self.request.user.userprofile.is_university_verified = True
            self.request.user.userprofile.mysnu_username = username
            self.request.user.userprofile.save()

            self.request.user.email = username + "@snu.ac.kr"
            self.request.user.save()

            return Response(status=status.HTTP_200_OK)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)


class VerifySNUMysnuEmail(VerifySNUBase):

    def post(self, request, *args, **kwargs):
        username = request.data.get('username', None)
        university = University.objects.get(slug="snu")

        self.request.user.userprofile.update_university(username, university)

        return Response(status=status.HTTP_200_OK)

snussum/snussum/views.py
from django.views.generic.base import TemplateView


class Home(TemplateView):
    template_name = "home.html"


class Dashboard(TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['dating_matched_today'] = self.request.user.userprofile.dating_matched_today()
        context['datings_matched_recently'] = self.request.user.userprofile.datings_matched_recently_except_today()
        return context

snussum/snussum/views/dashboard.py
from django.views.generic.base import TemplateView

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from users.decorators import university_verified_required, profile_verifed_required


class Dashboard(TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['dating_matched_today'] = self.request.user.userprofile.dating_matched_today()
        context['datings_matched_recently'] = self.request.user.userprofile.datings_matched_recently_except_today()
        return context

    @method_decorator(login_required)
    @method_decorator(university_verified_required)
    @method_decorator(profile_verifed_required)
    def dispatch(self, *args, **kwargs):
        return super(Dashboard, self).dispatch(*args, **kwargs)

snussum/snussum/views/home.py
from django.views.generic.base import TemplateView

from relationships.models.self_dating import SelfDating


class Home(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['self_datings'] = SelfDating.objects.order_by('-ends_at')[:3]
        return context


class About(TemplateView):
    template_name = "about.html"


class Browser(TemplateView):
    template_name = "browser.html"

snussum/snussum/views/rules.py
from django.views.generic.base import TemplateView


class Privacy(TemplateView):
    template_name = "rules/privacy.html"


class Service(TemplateView):
    template_name = "rules/service.html"

snussum/users/views/profile.py
from django.views.generic import View
from django.views.generic.edit import UpdateView
from django.views.generic.base import TemplateView

from django.utils.decorators import method_decorator
from users.decorators import university_verified_required, profile_verifed_required
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from users.models.user_profile import UserProfile
from django.contrib.auth.models import User

from users.forms.profile import UserProfileInformationForm, UserProfileAccountEmailForm, \
    UserProfileAccountPhonenumberForm, UserProfileImageForm

from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.contrib import messages


class Profile(TemplateView):
    template_name = "users/profile.html"

    @method_decorator(university_verified_required)
    @method_decorator(profile_verifed_required)
    def dispatch(self, *args, **kwargs):
        return super(Profile, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Profile, self).get_context_data(**kwargs)
        context['information_form'] = UserProfileInformationForm(instance=self.request.user.userprofile)
        return context


class UpdateUserBase(View):
    model = User

    @method_decorator(require_POST)
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UpdateUserBase, self).dispatch(*args, **kwargs)

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse("users:profile")


class UpdateUserProfileBase(UpdateUserBase):
    model = UserProfile

    def get_object(self):
        return self.request.user.userprofile


class UpdateUserProfileInformation(UpdateUserProfileBase, UpdateView):
    model = UserProfile
    fields = ['nickname', 'profile_introduce', 'age', 'height', 'region']

    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO,
                             '프로필이 성공적으로 업데이트 되었습니다. 감사합니다.',
                             extra_tags="success")
        return super(UpdateUserProfileInformation, self).form_valid(form)


class UpdateUserProfileImage(UpdateUserProfileBase, UpdateView):
    form_class = UserProfileImageForm

    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO,
                             '프로필 사진이 성공적으로 업데이트 되었습니다.',
                             extra_tags="success")
        return super(UpdateUserProfileImage, self).form_valid(form)


class UpdateUserProfileAccountEmail(UpdateUserBase, UpdateView):
    fields = ['email']

    def form_valid(self, form):
        messages.add_message(self.request, messages.INFO,
                             '이메일이 성공적으로 업데이트 되었습니다. 앞으로의 이메일 알림은 새롭게 등록한 이메일로 발송됩니다.',
                             extra_tags="success")
        return super(UpdateUserProfileAccountEmail, self).form_valid(form)


class UpdateUserProfileAccountPhonenumber(UpdateUserProfileBase, UpdateView):
    fields = ['phonenumber']

    def form_valid(self, form):
        phonenumber = form.cleaned_data['phonenumber']
        self.request.user.userprofile.update_phonenumber(phonenumber.replace("-", ""))
        messages.add_message(self.request, messages.INFO,
                             '연락처가 성공적으로 업데이트 되었습니다. SMS로 발송된 인증 링크를 확인해주세요',
                             extra_tags="success")
        return super(UpdateUserProfileAccountPhonenumber, self).form_valid(form)

    def form_invalid(self, form):
        messages.add_message(self.request, messages.INFO, "연락처가 업데이트되지 않았습니다. 이 문제가 지속적으로 발생할 경우 고객센터로 문의 부탁드립니다.",
                             extra_tags="danger")
        return redirect(self.get_success_url())


class UpdateUserProfileCondition(UpdateUserProfileBase, UpdateView):
    fields = ['age_condition', 'height_condition', 'region_condition']

    def form_valid(self, form):
        self.object.region_condition = self.request.POST.getlist("region_condition")
        self.object.save()

        messages.add_message(self.request, messages.INFO,
                             '매칭 조건이 성공적으로 업데이트 되었습니다. 감사합니다.',
                             extra_tags="success")
        return super(UpdateUserProfileCondition, self).form_valid(form)


class Notification(TemplateView):
    template_name = "users/notification.html"

    @method_decorator(university_verified_required)
    @method_decorator(profile_verifed_required)
    def dispatch(self, *args, **kwargs):
        return super(Notification, self).dispatch(*args, **kwargs)

snussum/snussum/templates/users/login.html
{% extends "_base.html" %}

{% block title %}로그인 - 썸타는 서울대학교 :: 스누썸{% endblock %}

{% block content %}
<section id="login">

  <section class="container">
    <div class="row">
      <div class="page-header text-center">
        <h1 class="jua">로그인 <small class="jua">하고 오늘의 썸 확인하기</small></h1>
        <p>서울대학생의, 서울대학생에 의한, 서울대학생을 위한 소개팅</p>
      </div>
    </div>
  </section>

  <section class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-sm-12 col-xs-12">
        <form action="{% url 'users:login' %}" method="post" accept-charset="utf-8">{% csrf_token %}
          {% if form.errors %}
            <p class="small danger">
              * 아이디와 비밀번호가 정확하지 않습니다. 불편하시더라도 다시 한번 확인 부탁드립니다.
            </p>
          {% endif %}
          <div class="form-group">
            <label for="">아이디</label> <span class="small danger">* 아이디를 정확하게 입력해주세요.</span>
            <input id="id_username" class="form-control" maxlength="30" name="username" type="text" placeholder="아이디" required>
          </div>
          <div class="form-group">
            <label for="">비밀번호</label> <span class="small danger">* 비밀번호를 정확하게 입력해주세요.</span>

            <input id="id_password" class="form-control" name="password" type="password" placeholder="비밀번호" required>
          </div>
          <button type="submit" class="text-center btn-snussum-darkgrey">
            <i class="fa fa-sign-in"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;스누썸 계정으로 로그인
          </button>
        </form>

        <div class="pull-right">
          <p class="small">
            <i class="fa fa-question-circle"></i>
            비밀번호를 잊으셨나요? <a href="{% url "users:password-reset" %}">비밀번호 찾기</a>
          </p>
        </div>
        <div class="row"></div>

        <hr/>

        <section>
          <a href="{% url "social:begin" backend="kakao" %}" class="text-center social-login social-login-kakao"><i class="fa fa-comment"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;카카오 계정으로 로그인</a>
          <a href="{% url "social:begin" backend="facebook" %}" class="text-center social-login social-login-facebook"><i class="fa fa-facebook"></i>&nbsp;&nbsp;&nbsp;&nbsp;페이스북 계정으로 로그인</a>
        </section>
      </div>
    </div>
  </section>

</section>
{% endblock %}

snussum/snussum/templates/users/notification.html
{% extends "_base.html" %}

{% block title %}알람 전체보기 - 썸타는 서울대학교 :: 스누썸{% endblock %}

{% block content %}
<section id="notifications">

  <section class="container">
    <div class="row">
      <div class="page-header text-center">
        <h1 class="jua">알림센터 <small class="jua">Notifications</small></h1>
        <p>데이트 매칭 정보, 댓글 정보 등에 대한 알림을 확인하실 수 있습니다</p>
      </div>
    </div>

    <section id="notifications" class="container">
      <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
        <ul class="notifications">
          {% for notification in user.notifications.all %}
            {% include "users/_notifications/_notification.html" with notification=notification %}
          {% endfor %}
        </ul>
      </div>
    </section>
  </section>

</section>
{% endblock %}

snussum/snussum/templates/users/password_reset.html
{% extends "_base.html" %}

{% block title %}비밀번호 찾기 - 썸타는 서울대학교 :: 스누썸{% endblock %}

{% block content %}
<section id="password-reset">
  <section class="container">
    <div class="row">
      <div class="page-header text-center">
        <h1 class="jua">비밀번호 재설정</h1>
        <p>
          비밀번호를 잊으신경우, 비밀번호 재설정을 통해서 새로운 비밀번호를
          설정할 수 있습니다. 
        </p>
      </div>
    </div>
  </section>

  <section class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-sm-12 col-xs-12">
        <p>
        계정에 등록된 이메일이나 휴대전화 문자메시지를 통해서 새로운 임시 비밀번호를 보내드리겠습니다.
        </p>

        <div class="form-group">
          <input type="email" required value="" name="" id="email" class="form-control" placeholder="contact@snussum.com" />
          <button type="submit" class="text-center btn-snussum-darkgrey">
            <i class="fa fa-envelope"></i>&nbsp;&nbsp;&nbsp;이메일을 이용하여 비밀번호 찾기
          </button>
        </div>

        <div class="form-group">
          <input type="tel" required value="" name="" id="phonenumber" class="form-control" placeholder="010-1234-5678" />
          <button type="submit" class="text-center btn-snussum-darkgrey">
            <i class="fa fa-envelope"></i>&nbsp;&nbsp;&nbsp;휴대폰을 이용하여 비밀번호 찾기
          </button>
        </div>
      </div>
    </div>
  </section>
</section>

<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
  var section = $("section#password-reset");
  
  var input_email = $(section).find("input#email");
  var input_phonenumber = $(section).find("input#phonenumber");

  var form_email = $(input_email).parent("div.form-group");
  var form_phonenumber = $(input_phonenumber).parent("div.form-group");

  $(form_email).find("button").click(function(){
    var email = $(input_email).val();
    var data = {'email': email};

    $.ajax({
      url: '/api/users/password/reset/',
      type: 'POST',
      data: data,
      success: function(result){
        $.notify({message: "이메일을 통해서 성공적으로 인증되었습니다. 계정과 연동된 이메일, 문자메시지를 통해서 새로운 비밀번호를 발송하였습니다."},
                 {type: "success"});
      },
      error: function(result){
        $.notify({message: "입력하신 이메일과 연동되어 있는 계정이 없습니다. 다시 한번 확인 후 입력 부탁드립니다. 감사합니다."},
                 {type: "danger"});
      }
    });
  });

  $(form_phonenumber).find("button").click(function(){
    var phonenumber = $(input_phonenumber).val().replace(/-/gi, "");
    var data = {'phonenumber': phonenumber};

    $.ajax({
      url: '/api/users/password/reset/',
      type: 'POST',
      data: data,
      success: function(result){
        $.notify({message: "휴대폰 인증을 통해서 성공적으로 인증되었습니다. 계정과 연동된 이메일, 문자메시지를 통해서 새로운 비밀번호를 발송하였습니다."},
                 {type: "success"});
      },
      error: function(result){
        $.notify({message: "입력하신 휴대전화번호와 연동되어 있는 계정이 없습니다. 다시 한번 확인 후 입력 부탁드립니다. 감사합니다."},
                 {type: "danger"});
      }
    });
  });
});
</script>
{% endblock %}

snussum/snussum/templates/users/signup.html
{% extends "_base.html" %}

{% block title %}회원가입 - 썸타는 서울대학교 :: 스누썸{% endblock %}

{% block content %}
<section id="signup">

  <section class="container">
    <div class="row">
      <div class="page-header text-center">
        <h1 class="jua">회원가입 <small class="jua">하고 썸타기</small></h1>
        <p>서울대학생의, 서울대학생에 의한, 서울대학생을 위한 소개팅</p>
      </div>
    </div>
  </section>

  <section class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-sm-12 col-xs-12">
        <section>
          <a href="{% url "social:begin" backend="kakao" %}" class="text-center social-login social-login-kakao"><i class="fa fa-comment"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;카카오 계정으로 회원가입</a>
          <a href="{% url "social:begin" backend="facebook" %}" class="text-center social-login social-login-facebook"><i class="fa fa-facebook"></i>&nbsp;&nbsp;&nbsp;&nbsp;페이스북 계정으로 회원가입</a>
        </section>
        <hr />

        <form action="{% url 'users:signup' %}" method="post" accept-charset="utf-8">{% csrf_token %}
          {% if form.errors %}
            <p class="small danger">
              * 입력하신 정보가 올바르지 않습니다. 불편하시더라도 다시 한번 확인 부탁드립니다.
            </p>
          {% endif %}
          <div class="form-group">
            <label for="">아이디</label> <span class="small danger">* 아이디를 정확하게 입력해주세요.</span>
            <input id="id_username" class="form-control" maxlength="30" name="username" type="text" placeholder="아이디" required>
          </div>
          <div class="form-group">
            <label for="">비밀번호</label> <span class="small danger">* 비밀번호를 정확하게 입력해주세요.</span>

            <input id="id_password1" class="form-control" name="password1" type="password" placeholder="비밀번호" required>
          </div>
          <div class="form-group">
            <label for="">비밀번호 확인</label> <span class="small danger">* 비밀번호가 일치하지 않습니다.</span> <span class="small success">* 입력하신 비밀번호가 일치합니다.</span>
            <input id="id_password2" class="form-control" name="password2" type="password" placeholder="비밀번호 확인" required>
          </div>
          <button type="submit" class="text-center btn-snussum-darkgrey">
            <i class="fa fa-sign-in"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;스누썸 계정으로 회원가입
          </button>
        </form>

        <div class="pull-right">
          <p class="small">
            <i class="fa fa-question-circle"></i>
            이미 회원이신가요? <a href="{% url "users:login" %}">로그인</a>
          </p>
        </div>
      </div>
    </div>
  </section>
  
</section>
{% endblock %}