snussum/api/urls.py
from django.conf.urls import patterns, url

from api.views.update_profile import UpdateProfileUniversity, UpdateProfileNickname,\
    UpdateProfileIntroduce, UpdateProfileGender, ResetPassword, UpdateProfileConditions
from api.views.messages import APIMessageSMS, APIMessageEmail, ContactAdmin
from api.views.messages import APIMessageSMS, APIMessageEmail
from api.views.datings import DatingComment
from api.views.verify import VerifySNUSnulifeLogin, VerifySNUMysnuLogin, VerifySNUMysnuEmail


urlpatterns = patterns(
    '',

    url(r'^login/$', 'rest_framework_jwt.views.verify_jwt_token'),
    url(r'^users/university/$', UpdateProfileUniversity.as_view(), name='update-university'),
    url(r'^users/nickname/$', UpdateProfileNickname.as_view(), name='update-nickname'),
    url(r'^users/introduce/$', UpdateProfileIntroduce.as_view(), name='update-introduce'),
    url(r'^users/gender/$', UpdateProfileGender.as_view(), name='update-gender'),
    url(r'^users/conditions/$', UpdateProfileConditions.as_view(), name='update-conditions'),

    url(r'^users/password/reset/$', ResetPassword.as_view(), name='reset-password'),

    url(r'^ssum/(?P<hash_id>\w+)/comment/$', DatingComment.as_view(), name='dating-comment'),

    url(r'^sms/$', APIMessageSMS.as_view(), name='sms'),
    url(r'^email/$', APIMessageEmail.as_view(), name='email'),

    # SNU Verifications
    url(r'^users/snulife/login/$', VerifySNUSnulifeLogin.as_view(), name='snulife-login'),
    url(r'^users/mysnu/login/$', VerifySNUMysnuLogin.as_view(), name='mysnu-login'),
    url(r'^users/mysnu/email/$', VerifySNUMysnuEmail.as_view(), name='mysnu-email'),

    url(r'^contact/$', ContactAdmin.as_view(), name='contact'),
)

snussum/snussum/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from snussum.views import Home, Dashboard, About, Browser
from snussum.views.rules import Privacy, Service

from relationships.views.dating import DatingList, DatingDetail, DatingAccept, DatingRefuse, DatingRatingCreate
from relationships.views.self_dating import SelfDatingCreate, SelfDatingDetail, \
    SelfDatingApplyCreate, SelfDatingApplyAccept, SelfDatingApplyRefuse, \
    SelfDatingList

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from snussum.sitemaps import sitemaps


urlpatterns = [
    # Django Default
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^%s/' % settings.ADMIN_URL, include(admin.site.urls)),

    url(r'^robots\.txt$', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # Project Libraries
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^summernote/', include('django_summernote.urls')),

    # Project Urls
    url(r'^$', Home.as_view(), name='home'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^browsers/$', Browser.as_view(), name='browsers'),

    url(r'^rules/service/$', Service.as_view(), name='rule-service'),
    url(r'^rules/privacy/$', Privacy.as_view(), name='rule-privacy'),

    url(r'^today/$', Dashboard.as_view(), name='dashboard'),

    url(r'^ssum/$', DatingList.as_view(), name='dating-list'),
    url(r'^ssum/(?P<slug>\w+)/$', DatingDetail.as_view(), name='dating-detail'),
    url(r'^ssum/(?P<slug>\w+)/accept/$', DatingAccept.as_view(), name='dating-accept'),
    url(r'^ssum/(?P<slug>\w+)/refuse/$', DatingRefuse.as_view(), name='dating-refuse'),
    url(r'^ssum/(?P<slug>\w+)/rating/$', DatingRatingCreate.as_view(), name='dating-rating'),

    url(r'^wanted/$', SelfDatingList.as_view(), name='self-dating-list'),
    url(r'^wanted/new/$', SelfDatingCreate.as_view(), name='self-dating-new'),
    url(r'^wanted/(?P<slug>\w+)/$', SelfDatingDetail.as_view(), name='self-dating-detail'),
    url(r'^wanted/(?P<slug>\w+)/apply/$', SelfDatingApplyCreate.as_view(), name='self-dating-apply'),

    url(r'^wanted/(?P<slug>\w+)/apply/(?P<self_dating_apply_hash_id>\w+)/accept/$',
        SelfDatingApplyAccept.as_view(),
        name='self-dating-apply-accept'),
    url(r'^wanted/(?P<slug>\w+)/apply/(?P<self_dating_apply_hash_id>\w+)/refuse/$',
        SelfDatingApplyRefuse.as_view(),
        name='self-dating-apply-refuse'),

    url(r'^', include('users.urls', namespace='users')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^snusex/', include('snusex.urls', namespace='snusex')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

snussum/users/urls.py
from django.conf.urls import patterns, url

from users.views.verify import VerifyUniversity, VerifyUniversitySNU, VerifyProfile
from users.views.profile import Profile, Notification, UpdateUserProfileInformation, UpdateUserProfileAccountEmail, \
    UpdateUserProfileAccountPhonenumber, UpdateUserProfileCondition, UpdateUserProfileImage
from users.views.auth import PasswordReset


urlpatterns = patterns(
    '',

    url(r'^login/$', 'users.views.auth.login', name='login'),
    url(r'^signup/$', 'users.views.auth.signup', name='signup'),
    url(r'^logout/$', 'users.views.auth.logout', name='logout'),

    url(r'^password/reset/$', PasswordReset.as_view(), name='password-reset'),

    url(r'^profile/$', Profile.as_view(), name='profile'),
    url(r'^notifications/$', Notification.as_view(), name='notification'),

    # Update UserProfile
    url(r'^profile/information/$', UpdateUserProfileInformation.as_view(), name='update-profile-information'),
    url(r'^profile/image/$', UpdateUserProfileImage.as_view(), name='update-profile-image'),
    url(r'^profile/account/email/$', UpdateUserProfileAccountEmail.as_view(), name='update-profile-account-email'),
    url(r'^profile/account/phonenumber/$',
        UpdateUserProfileAccountPhonenumber.as_view(),
        name='update-profile-account-phonenumber'),
    url(r'^profile/condition/$', UpdateUserProfileCondition.as_view(), name='update-profile-condition'),

    url(r'^verify/univ/$', VerifyUniversity.as_view(), name='verify-univ'),
    url(r'^verify/snu/$', VerifyUniversitySNU.as_view(), name='verify-snu'),
    url(r'^verify/profile/$', VerifyProfile.as_view(), name='verify-profile'),

    url(r'^verify/university/(?P<university_verification_token>\w+)/$',
        'users.views.verify.university_verification',
        name='university-verification'
        ),
    url(r'^verify/phonenumber/(?P<phonenumber_verification_token>\w+)/$',
        'users.views.verify.phonenumber_verification',
        name='phonenumber-verification'
        ),
)

snussum/users/models/user_profile.py
from django.db import models
from django.contrib.postgres.fields import IntegerRangeField, ArrayField

from django.db.models.signals import post_save

from django.contrib.auth.models import User
from relationships.models.dating import Dating
from users.models.university import University

from users.tasks.password import send_password_reset_sms, \
    send_password_reset_email
from users.tasks.verification import send_phonenumber_verification_sms, \
    send_university_verification_email

from users.utils.hashids import get_encoded_user_profile_hashid

from datetime import date
from hashlib import sha1
from random import random
import datetime

from django.templatetags.static import static


class UserProfileManager(models.Manager):

    def users(self):
        return User.objects.all()

    def boys(self):
        return self.users().filter(userprofile__is_boy=True)

    def girls(self):
        return self.users().filter(userprofile__is_boy=False)

    def users_university_verified(self):
        return self.users().filter(userprofile__is_university_verified=True)

    def boys_university_verified(self):
        return self.boys().filter(userprofile__is_university_verified=True)

    def girls_university_verified(self):
        return self.girls().filter(userprofile__is_university_verified=True)

    def users_profile_verified(self):
        return self.users_university_verified().filter(
            userprofile__is_boy__isnull=False,
            userprofile__nickname__isnull=False,
            userprofile__profile_introduce__isnull=False,
        )

    def boys_profile_verified(self):
        return self.boys_university_verified().filter(
            userprofile__nickname__isnull=False,
            userprofile__profile_introduce__isnull=False,
        )

    def girls_profile_verified(self):
        return self.girls_university_verified().filter(
            userprofile__nickname__isnull=False,
            userprofile__profile_introduce__isnull=False,
        )

    def users_joined_today(self):
        return self.users().filter(
            date_joined__range=(datetime.date.today(), datetime.date.today() + datetime.timedelta(1))
        )

    def boys_joined_today(self):
        return self.boys().filter(
            date_joined__range=(datetime.date.today(), datetime.date.today() + datetime.timedelta(1))
        )

    def girls_joined_today(self):
        return self.girls().filter(
            date_joined__range=(datetime.date.today(), datetime.date.today() + datetime.timedelta(1))
        )

    def users_joined_yesterday(self):
        return self.users().filter(
            date_joined__range=(datetime.date.today() - datetime.timedelta(1), datetime.date.today())
        )

    def boys_joined_yesterday(self):
        return self.boys().filter(
            date_joined__range=(datetime.date.today() - datetime.timedelta(1), datetime.date.today())
        )

    def girls_joined_yesterday(self):
        return self.girls().filter(
            date_joined__range=(datetime.date.today() - datetime.timedelta(1), datetime.date.today())
        )

    def randomized_profile_verified_boys(self):
        return self.boys_profile_verified().order_by("?")

    def randomized_profile_verified_girls(self):
        return self.girls_profile_verified().order_by("?")

    def _is_boys_more_than_girls(self):
        return self.boys_profile_verified().count() >= self.girls_profile_verified().count()

    def divide_groups(self):
        """
        return (Bigger, Smaller)
        """
        if self._is_boys_more_than_girls():
            return (self.randomized_profile_verified_boys(), self.randomized_profile_verified_girls())
        return (self.randomized_profile_verified_girls(), self.randomized_profile_verified_boys())


def _profile_image_upload_to(instance, filename):
    return "profile/%s" % instance.hash_id + \
        "-" + sha1(str(random()).encode('utf-8')).hexdigest()[:8] + \
        "." + filename.split(".")[-1]


class UserProfile(models.Model):
    objects = UserProfileManager()

    user = models.OneToOneField(User, unique=True, primary_key=True)
    hash_id = models.CharField(max_length=8, unique=True, blank=True, null=True)

    nickname = models.CharField(max_length=8, blank=True, null=True, unique=True)
    is_boy = models.NullBooleanField(default=None, blank=True, null=True)

    # University Validation ( Email Validation )
    university = models.ForeignKey(University, blank=True, null=True)
    is_university_verified = models.BooleanField(default=False)
    university_verification_token = models.CharField(max_length=32, null=True, blank=True)

    # MySNU Username, SNULife Username - 멀티계정 방지
    mysnu_username = models.CharField(max_length=16, blank=True, null=True, unique=True)
    snulife_username = models.CharField(max_length=16, blank=True, null=True, unique=True)

    # PhoneNumber Validation
    phonenumber = models.CharField(max_length=13, default=None, blank=True, null=True, unique=True)
    is_phonenumber_verified = models.BooleanField(default=False)
    phonenumber_verification_token = models.CharField(max_length=32, null=True, blank=True)

    profile_introduce = models.TextField(blank=True, null=True)

    profile_image = models.ImageField(upload_to=_profile_image_upload_to, blank=True, null=True)

    is_dating_enabled = models.BooleanField(default=True)

    # Introduce
    age = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    weight = models.IntegerField(blank=True, null=True)

    REGION_CHOICES = (
        # 국내
        ('서울', '서울특별시'),
        ('부산', '부산광역시'),
        ('인천', '인천광역시'),
        ('대구', '대구광역시'),
        ('광주', '광주광역시'),
        ('대전', '대전광역시'),
        ('울산', '울산광역시'),
        ('경기', '경기도'),
        ('강원', '강원도'),
        ('충북', '충청북도'),
        ('충남', '충청남도'),
        ('경북', '경상북도'),
        ('경남', '경상남도'),
        ('전북', '전라북도'),
        ('전남', '전라남도'),
        ('제주', '제주도'),

        # 해외
        ('미국', '미국'),
        ('중국', '중국'),
        ('일본', '일본'),

        # 기타
        ('절망', '절망의땅301동'),
        ('멸망', '멸망의땅301동'),
        ('슬픔', '슬픔의땅301동'),
        ('좌절', '좌절의땅301동'),
    )
    region = models.CharField(max_length=2, choices=REGION_CHOICES, blank=True, null=True)

    # Condition
    age_condition = IntegerRangeField(blank=True, null=True)
    height_condition = IntegerRangeField(blank=True, null=True)
    weight_condition = IntegerRangeField(blank=True, null=True)
    region_condition = ArrayField(models.CharField(max_length=2), blank=True, null=True)

    def _profile_image_url(self):
        if self.profile_image:
            return self.profile_image.url

        if self.is_boy:
            return static('img/profile/boy.jpg')
        else:
            return static('img/profile/girl.jpg')
    profile_image_url = property(_profile_image_url)

    def _is_profile_verified(self):
        if self.is_boy is not None and \
                self.nickname and \
                self.profile_introduce and len(self.profile_introduce) >= 50:
            return True
        return False
    is_profile_verified = property(_is_profile_verified)

    def _is_girl(self):
        return not is_boy
    is_girl = property(_is_girl)

    def __str__(self):
        return self.user.username

    def _get_social_auth_profile(self, provider):
        return self.user.social_auth.filter(provider=provider).first()

    def facebook(self):
        return self._get_social_auth_profile("facebook")

    def kakao(self):
        return self._get_social_auth_profile("kakao")

    def reset_password(self):
        new_password = sha1(str(random()).encode('utf-8')).hexdigest()[:6]
        self.user.set_password(new_password)
        self.user.save()

        send_password_reset_sms(self.user, new_password)
        send_password_reset_email(self.user, new_password)

    def datings_matched(self):
        if self.is_boy:
            return self.user.dating_girls.all()
        return self.user.dating_boys.all()

    def dating_matched_today(self):
        return self.datings_matched().filter(matched_at=date.today()).first()

    def datings_matched_recently_except_today(self):
        return self.datings_matched().exclude(matched_at=date.today())[:3]

    def dating_matched_with(self, partner):
        if self.is_boy:
            return Dating.objects.filter(boy=self.user, girl=partner).first()
        return Dating.objects.filter(boy=partner, girl=self.user).first()

    def is_dating_available_with(self, partner):
        """
        매칭이 가능한지 여부를 파악한다.

        1. 기본 조건 검사 ( 기존 매칭 여부, 당일 매칭 여부 등 )
        2. 나의 조건 - 상대방 프로필 검사
        3. 나의 프로필 - 상대방 조건 검사
        """
        return not self.dating_matched_today() and \
            not partner.userprofile.dating_matched_today() and \
            not self.dating_matched_with(partner) and \
            self.is_conditions_available_with(partner) and \
            partner.userprofile.is_conditions_available_with(self.user)

    def is_conditions_available_with(self, partner):
        """
        모든 조건에 부합하는지 검사한다.
        """
        return self.is_age_condition_available_with(partner) and \
            self.is_height_condition_available_with(partner) and \
            self.is_region_condition_available_with(partner)

    def is_age_condition_available_with(self, partner):
        # 나이 조건에 상대방의 나이가 적합한지 확인한다.

        if not self.age_condition:
            # 나이 조건이 설정되지 않았다면 ( UserProfile Default )
            # 상대방의 나이와 상관 없이 True를 반환한다.
            return True
        elif self.age_condition and not partner.userprofile.age:
            # 나이 조건이 설정되었으나 상대방의 나이가 없는 경우
            return False
        elif partner.userprofile.age in self.age_condition:
            # 나이 조건이 설정되었고,
            # 상대방의 나이가 있는 경우,
            # 나이 조건에 상대방의 나이가 포함된다면 True를 반환한다.
            return True
        else:
            # 나이 조건에 상대방의 나이가 포함되지 않는다면 True를 반환한다.
            return False

snussum/snussum/views.py
from django.views.generic.base import TemplateView


class Home(TemplateView):
    template_name = "home.html"


class Dashboard(TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['dating_matched_today'] = self.request.user.userprofile.dating_matched_today()
        context['datings_matched_recently'] = self.request.user.userprofile.datings_matched_recently_except_today()
        return context

snussum/snussum/views/home.py
from django.views.generic.base import TemplateView

from relationships.models.self_dating import SelfDating


class Home(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['self_datings'] = SelfDating.objects.order_by('-ends_at')[:3]
        return context


class About(TemplateView):
    template_name = "about.html"


class Browser(TemplateView):
    template_name = "browser.html"

snussum/snussum/templates/users/verify/profile.html
{% extends "_base.html" %}
{% load staticfiles %}

{% block title %}기본정보 입력 - 썸타는 서울대학교 :: 스누썸{% endblock %}

{% block content %}
  <section id="verify-profile">
    {{ form.media }}
    <form action="" method="POST" accept-charset="utf-8">{% csrf_token %}
      <section class="container">
        <div class="row">
          <div class="page-header text-center">
            <h1>기본정보 입력 <small>Personal Info</small></h1>
            <p>
              성실한 개인정보 입력은 상대방에 대한 예의입니다
            </p>
          </div>
        </div>
      </section>

      <section class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-4 col-md-offset-4">

            <label for="">필수정보</label>
            <span class="success small">
              <i class="fa fa-check"></i>
              서비스 이용을 위해서 필수적으로 입력 부탁드립니다.
            </span>

            <section id="verify-profile-nickname">
              <div class="form-group border {% if user.userprofile.nickname %}border-success{% endif %}">
                <label for="">닉네임 <span class="small">( 매칭 시 상대방에게 표시되는 이름 )</span></label>
                <input type="text" value="{% if user.userprofile.nickname %}{{ user.userprofile.nickname }}{% endif %}" required placeholder="{{ user.username }}" name="nickname" id="id_nickname" class="form-control" maxlength=8/>
              </div>
            </section>

            <section id="verify-profile-gender">
              <div class="form-group border">
                <label>성별 <span class="small">( 선택 후 변경이 불가합니다 )</span></label>

                <input type="text" name="is_boy" id="id_is_boy" class="hide" required/>

                <div class="text-center">
                  <img id="boy" class="" src="{% static "img/profile/transparent/boy.png" %}" alt=""/>
                  <img id="boy_makeup" class="makeup" src="{% static "img/profile/transparent/boy_makeup.png" %}" alt=""/>

                  <img id="girl" src="{% static "img/profile/transparent/girl.png" %}" alt=""/>
                  <img id="girl_makeup" class="makeup" src="{% static "img/profile/transparent/girl_makeup.png" %}" alt=""/>
                </div>
              </div>
            </section>

            <section id="verify-profile-introduce">
              <div class="form-group border {% if user.userprofile.profile_introduce|length > 50 %}border-success{% endif %}">
                <label for="">자기소개</label>
                <p class="small danger">
                  * 매칭 상대방을 위해서 자기소개는 반드시 50자 이상 작성해주셔야 합니다.
                  조금 불편하시더라고, 더 나은 서비스를 위해서 성실한 작성 부탁드리겠습니다. 감사합니다.
                </p>
                <p class="small success">
                  * 성실한 자기소개를 작성해주셔서 진심으로 감사드립니다.
                </p>

                {{ form.profile_introduce }}
              </div>
            </section>

            <hr/>
              
            <label for="">선택정보</label>
            <span class="success small">
              <i class="fa fa-check"></i>
              선택적으로 입력하실 수 있는 정보입니다.
            </span>

            <section id="verify-profile-age">
              <div class="form-group border {% if user.userprofile.age %}border-success{% endif %}">
                <label for="">나이</label>
                <input type="text" value="{% if user.userprofile.age %}{{ user.userprofile.age }}{% endif %}" placeholder="23" name="age" id="id_age" class="form-control" >
              </div>
            </section>

            <section id="verify-profile-height">
              <div class="form-group border {% if user.userprofile.height %}border-success{% endif %}">
                <label for="">키 ( 신장 )</label>
                <input type="text" value="{% if user.userprofile.height %}{{ user.userprofile.height }}{% endif %}" placeholder="168" name="height" id="id_height" class="form-control" >
              </div>
            </section>

            <button type="submit" class="text-center btn-snussum-red" disabled>
              <i class="fa fa-sign-in"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;프로필 업데이트
            </button>
          </div>
        </div>
      </section>

    </form>
  </section>
{% endblock %}

snussum/snussum/templates/users/verify/snu.html
{% extends "_base.html" %}

{% block title %}서울대학교 인증 - 썸타는 서울대학교 :: 스누썸{% endblock %}

{% block content %}
<section id="verify-snu">
  <section class="container">
    <div class="row">
      <div class="page-header text-center">
        <h1 class="jua">서울대학교 인증
          <small class="jua hidden-xs hidden-sm">하고 빨리 소개팅받기</small>
        </h1>
        <p>썸타는 서울대, 스누썸은 다양한 인증 방법을 지원하고 있습니다.</p>
      </div>
    </div>
  </section>

  <section class="container">
    <div class="row snu-verification-lists text-center">
      <ul>
        <li class="col-sm-4 active snu-verification-list">
          <div>
            <a href="#mysnu-email" data-toggle="tab" aria-controls="mysnu-email">
              마이스누 x 이메일
            </a>
          </div>
        </li>
        <li class="col-sm-4 snu-verification-list">
          <div>
            <a href="#mysnu-login" data-toggle="tab" aria-controls="mysnu-login">
              마이스누 x 로그인
            </a>
          </div>
        </li>
        <li class="col-sm-4 snu-verification-list">
          <div>
            <a href="#snulife-login" data-toggle="tab" aria-controls="snulife-login">
              스누라이프 x 로그인
            </a>
          </div>
        </li>
      </ul>
    </div>

    <div class="row snu-verification-details">
      <div role="tabpanel" id="mysnu-email" class="snu-verification-detail animated fadeIn active">
        {% include "users/verify/_snu/_mysnu_email.html" %}
      </div>
      <div role="tabpanel" id="mysnu-login" class="snu-verification-detail animated fadeIn">
        {% include "users/verify/_snu/_mysnu_login.html" %}
      </div>
      <div role="tabpanel" id="snulife-login" class="snu-verification-detail animated fadeIn">
        {% include "users/verify/_snu/_snulife_login.html" %}
      </div>
    </div>
  </section>
  
</section>
{% endblock %}

snussum/snussum/templates/users/verify/univ.html
{% extends "_base.html" %}
{% load staticfiles %}

{% block title %}대학교 인증 - 썸타는 서울대학교 :: 스누썸{% endblock %}

{% block content %}
<section id="verify">

  <section id="verify-description" class="page-description">
    <div class="wrapper">
      <h1>학교 인증하기</h1>
      <p>썸타는 서울대, 스누썸 서비스를 이용하기 위해서는 학교 이메일을 통해서 이메일 인증을 거쳐야만 사용할 수 있습니다.</p>
    </div>
  </section>

  <section id="universities">
    <div class="wrapper">
      <ul>
        {% for university in universities %}
        <li class="university" data-name="{{ university.full_name }}" data-university="{{ university.id }}" data-email="{{ university.email }}">
        <img class="logo" src="{% static 'img/logo/' %}{{ university.slug }}.png" alt="{{ university }}"/>
          {{ university }}
        </li>
        {% endfor %}
      </ul>
    </div>
  </section>

  <section id="verify-summary">
    <div class="wrapper">
      <input type="text" value="{{ user.username }}" name="username"/><span id="university-email">@snu.ac.kr</span>

      <button type="submit">이메일 등록하기</button>
    </div>
  </section>

</section>

<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
  $("section#universities").find("img.logo").first().addClass("selected");

  $("li.university").click(function(){
    var university_name = $(this).data("name");
    var university_id = $(this).data("university");
    var university_email = $(this).data("email");

    $("img.selected").removeClass("selected");
    $(this).find("img").addClass("selected");

    $("span#university-email").text("@" + university_email);
  });

  $("section#verify-summary").find("button").click(function(){
    var university = $("img.selected").parent("li.university");

    var university = $(university).data("university");
    var username = $("section#verify-summary").find("input").val();

    var data = {
      'username': username,
      'university': university
    };

    $.ajax({
      url: '/api/users/university/',
      type: 'PUT',
      data: data,
      success: function(result) {
      }
    });
  });
});
</script>

{% endblock %}