snussum/api/urls.py
from django.conf.urls import patterns, url

from api.views.update_profile import UpdateProfileUniversity, UpdateProfileNickname,\
    UpdateProfileIntroduce, UpdateProfileGender, ResetPassword, UpdateProfileConditions
from api.views.messages import APIMessageSMS, APIMessageEmail, ContactAdmin
from api.views.messages import APIMessageSMS, APIMessageEmail
from api.views.datings import DatingComment
from api.views.verify import VerifySNUSnulifeLogin, VerifySNUMysnuLogin, VerifySNUMysnuEmail


urlpatterns = patterns(
    '',

    url(r'^login/$', 'rest_framework_jwt.views.verify_jwt_token'),
    url(r'^users/university/$', UpdateProfileUniversity.as_view(), name='update-university'),
    url(r'^users/nickname/$', UpdateProfileNickname.as_view(), name='update-nickname'),
    url(r'^users/introduce/$', UpdateProfileIntroduce.as_view(), name='update-introduce'),
    url(r'^users/gender/$', UpdateProfileGender.as_view(), name='update-gender'),
    url(r'^users/conditions/$', UpdateProfileConditions.as_view(), name='update-conditions'),

    url(r'^users/password/reset/$', ResetPassword.as_view(), name='reset-password'),

    url(r'^ssum/(?P<hash_id>\w+)/comment/$', DatingComment.as_view(), name='dating-comment'),

    url(r'^sms/$', APIMessageSMS.as_view(), name='sms'),
    url(r'^email/$', APIMessageEmail.as_view(), name='email'),

    # SNU Verifications
    url(r'^users/snulife/login/$', VerifySNUSnulifeLogin.as_view(), name='snulife-login'),
    url(r'^users/mysnu/login/$', VerifySNUMysnuLogin.as_view(), name='mysnu-login'),
    url(r'^users/mysnu/email/$', VerifySNUMysnuEmail.as_view(), name='mysnu-email'),

    url(r'^contact/$', ContactAdmin.as_view(), name='contact'),
)

snussum/snussum/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from snussum.views import Home, Dashboard, About, Browser
from snussum.views.rules import Privacy, Service

from relationships.views.dating import DatingList, DatingDetail, DatingAccept, DatingRefuse, DatingRatingCreate
from relationships.views.self_dating import SelfDatingCreate, SelfDatingDetail, \
    SelfDatingApplyCreate, SelfDatingApplyAccept, SelfDatingApplyRefuse, \
    SelfDatingList

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from snussum.sitemaps import sitemaps


urlpatterns = [
    # Django Default
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^%s/' % settings.ADMIN_URL, include(admin.site.urls)),

    url(r'^robots\.txt$', include('robots.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    # Project Libraries
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^summernote/', include('django_summernote.urls')),

    # Project Urls
    url(r'^$', Home.as_view(), name='home'),
    url(r'^about/$', About.as_view(), name='about'),
    url(r'^browsers/$', Browser.as_view(), name='browsers'),

    url(r'^rules/service/$', Service.as_view(), name='rule-service'),
    url(r'^rules/privacy/$', Privacy.as_view(), name='rule-privacy'),

    url(r'^today/$', Dashboard.as_view(), name='dashboard'),

    url(r'^ssum/$', DatingList.as_view(), name='dating-list'),
    url(r'^ssum/(?P<slug>\w+)/$', DatingDetail.as_view(), name='dating-detail'),
    url(r'^ssum/(?P<slug>\w+)/accept/$', DatingAccept.as_view(), name='dating-accept'),
    url(r'^ssum/(?P<slug>\w+)/refuse/$', DatingRefuse.as_view(), name='dating-refuse'),
    url(r'^ssum/(?P<slug>\w+)/rating/$', DatingRatingCreate.as_view(), name='dating-rating'),

    url(r'^wanted/$', SelfDatingList.as_view(), name='self-dating-list'),
    url(r'^wanted/new/$', SelfDatingCreate.as_view(), name='self-dating-new'),
    url(r'^wanted/(?P<slug>\w+)/$', SelfDatingDetail.as_view(), name='self-dating-detail'),
    url(r'^wanted/(?P<slug>\w+)/apply/$', SelfDatingApplyCreate.as_view(), name='self-dating-apply'),

    url(r'^wanted/(?P<slug>\w+)/apply/(?P<self_dating_apply_hash_id>\w+)/accept/$',
        SelfDatingApplyAccept.as_view(),
        name='self-dating-apply-accept'),
    url(r'^wanted/(?P<slug>\w+)/apply/(?P<self_dating_apply_hash_id>\w+)/refuse/$',
        SelfDatingApplyRefuse.as_view(),
        name='self-dating-apply-refuse'),

    url(r'^', include('users.urls', namespace='users')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^snusex/', include('snusex.urls', namespace='snusex')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

snussum/users/urls.py
from django.conf.urls import patterns, url

from users.views.verify import VerifyUniversity, VerifyUniversitySNU, VerifyProfile
from users.views.profile import Profile, Notification, UpdateUserProfileInformation, UpdateUserProfileAccountEmail, \
    UpdateUserProfileAccountPhonenumber, UpdateUserProfileCondition, UpdateUserProfileImage
from users.views.auth import PasswordReset


urlpatterns = patterns(
    '',

    url(r'^login/$', 'users.views.auth.login', name='login'),
    url(r'^signup/$', 'users.views.auth.signup', name='signup'),
    url(r'^logout/$', 'users.views.auth.logout', name='logout'),

    url(r'^password/reset/$', PasswordReset.as_view(), name='password-reset'),

    url(r'^profile/$', Profile.as_view(), name='profile'),
    url(r'^notifications/$', Notification.as_view(), name='notification'),

    # Update UserProfile
    url(r'^profile/information/$', UpdateUserProfileInformation.as_view(), name='update-profile-information'),
    url(r'^profile/image/$', UpdateUserProfileImage.as_view(), name='update-profile-image'),
    url(r'^profile/account/email/$', UpdateUserProfileAccountEmail.as_view(), name='update-profile-account-email'),
    url(r'^profile/account/phonenumber/$',
        UpdateUserProfileAccountPhonenumber.as_view(),
        name='update-profile-account-phonenumber'),
    url(r'^profile/condition/$', UpdateUserProfileCondition.as_view(), name='update-profile-condition'),

    url(r'^verify/univ/$', VerifyUniversity.as_view(), name='verify-univ'),
    url(r'^verify/snu/$', VerifyUniversitySNU.as_view(), name='verify-snu'),
    url(r'^verify/profile/$', VerifyProfile.as_view(), name='verify-profile'),

    url(r'^verify/university/(?P<university_verification_token>\w+)/$',
        'users.views.verify.university_verification',
        name='university-verification'
        ),
    url(r'^verify/phonenumber/(?P<phonenumber_verification_token>\w+)/$',
        'users.views.verify.phonenumber_verification',
        name='phonenumber-verification'
        ),
)

snussum/analytics/models/base.py
from django.db import models


class AnalyticsManagerBase(models.Manager):

    def create_analytics(self):
        instance = self.model()
        instance.save()
        return instance

    class Meta:
        abstract = True


class AnalyticsModelBase(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

snussum/analytics/models/demographic.py
from django.db import models

from django.dispatch import receiver
from django.db.models.signals import post_save

from analytics.models.base import AnalyticsManagerBase, AnalyticsModelBase

import datetime

from users.models.user_profile import UserProfile
from relationships.models.dating import Dating


class DemographicManager(AnalyticsManagerBase):
    pass


class Demographic(AnalyticsModelBase):
    objects = DemographicManager()

    # Date - 날짜의 경우에는 24시를 기준으로 새롭계 계산하므로 어제의 날짜로 생성
    date = models.DateField(default=datetime.date.today() - datetime.timedelta(1))

    # Basic Demographics
    users = models.IntegerField(blank=True, null=True)
    boys = models.IntegerField(blank=True, null=True)
    girls = models.IntegerField(blank=True, null=True)

    # Basic Demographics with University Verified
    users_university_verified = models.IntegerField(blank=True, null=True)
    boys_university_verified = models.IntegerField(blank=True, null=True)
    girls_university_verified = models.IntegerField(blank=True, null=True)

    # Basic Demographics with Profile Verified
    # - including is_boy, nickname, profile_introduce
    users_profile_verified = models.IntegerField(blank=True, null=True)
    boys_profile_verified = models.IntegerField(blank=True, null=True)
    girls_profile_verified = models.IntegerField(blank=True, null=True)

    # New Registered Deomographics
    users_joined_today = models.IntegerField(blank=True, null=True)
    boys_joined_today = models.IntegerField(blank=True, null=True)
    girls_joined_today = models.IntegerField(blank=True, null=True)

    # Datings Matched Demographics
    users_dating_matched_today = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.date)


@receiver(post_save, sender=Demographic)
def _calculate_demographic(sender, instance, created, **kwargs):
    if created:
        instance.users = UserProfile.objects.users().count()
        instance.boys = UserProfile.objects.boys().count()
        instance.girls = UserProfile.objects.girls().count()

        instance.users_university_verified = UserProfile.objects.users_university_verified().count()
        instance.boys_university_verified = UserProfile.objects.boys_university_verified().count()
        instance.girls_university_verified = UserProfile.objects.girls_university_verified().count()

        instance.users_profile_verified = UserProfile.objects.users_profile_verified().count()
        instance.boys_profile_verified = UserProfile.objects.boys_profile_verified().count()
        instance.girls_profile_verified = UserProfile.objects.girls_profile_verified().count()

        instance.users_joined_today = UserProfile.objects.users_joined_yesterday().count()
        instance.boys_joined_today = UserProfile.objects.boys_joined_yesterday().count()
        instance.girls_joined_today = UserProfile.objects.girls_joined_yesterday().count()

        instance.users_dating_matched_today = Dating.objects.datings_matched_yesterday().count()

        instance.save()

snussum/analytics/models/demographics.py
from django.db import models

from django.dispatch import receiver
from django.db.models.signals import post_save

from analytics.models.base import AnalyticsManagerBase, AnalyticsModelBase

import datetime

from users.models.user_profile import UserProfile


class DemographicsManager(AnalyticsManagerBase):
    pass


class Demographics(AnalyticsModelBase):
    objects = DemographicsManager()

    # Date - 날짜의 경우에는 24시를 기준으로 새롭계 계산하므로 어제의 날짜로 생성
    date = models.DateField(default=datetime.date.today() - datetime.timedelta(1))

    # Basic Demographics
    users = models.IntegerField(blank=True, null=True)
    boys = models.IntegerField(blank=True, null=True)
    girls = models.IntegerField(blank=True, null=True)

    # Basic Demographics with University Verified
    users_university_verified = models.IntegerField(blank=True, null=True)
    boys_university_verified = models.IntegerField(blank=True, null=True)
    girls_university_verified = models.IntegerField(blank=True, null=True)

    # Basic Demographics with Profile Verified
    # - including is_boy, nickname, profile_introduce
    users_profile_verified = models.IntegerField(blank=True, null=True)
    boys_profile_verified = models.IntegerField(blank=True, null=True)
    girls_profile_verified = models.IntegerField(blank=True, null=True)

    # New Registered Deomographics
    users_joined_today = models.IntegerField(blank=True, null=True)
    boys_joined_today = models.IntegerField(blank=True, null=True)
    girls_joined_today = models.IntegerField(blank=True, null=True)

    # Datings Matched Demographics
    users_dating_matched_today = models.IntegerField(blank=True, null=True)
    boys_dating_matched_today = models.IntegerField(blank=True, null=True)
    girls_dating_matched_today = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.date)


@receiver(post_save, sender=Demographics)
def _calculate_demographics(sender, instance, created, **kwargs):
    if created:
        instance.users = UserProfile.objects.users().count()
        instance.boys = UserProfile.objects.boys().count()
        instance.girls = UserProfile.objects.girls().count()

        instance.users_university_verified = UserProfile.objects.users_university_verified().count()
        instance.boys_university_verified = UserProfile.objects.boys_university_verified().count()
        instance.girls_university_verified = UserProfile.objects.girls_university_verified().count()

        instance.users_profile_verified = UserProfile.objects.users_profile_verified().count()
        instance.boys_profile_verified = UserProfile.objects.boys_profile_verified().count()
        instance.girls_profile_verified = UserProfile.objects.girls_profile_verified().count()

        instance.users_joined_today = UserProfile.objects.users_joined_yesterday().count()
        instance.boys_joined_today = UserProfile.objects.boys_joined_yesterday().count()
        instance.girls_joined_today = UserProfile.objects.girls_joined_yesterday().count()

        instance.save()

snussum/relationships/models/comment.py
from django.core.urlresolvers import reverse
from django.db import models

from django.contrib.auth.models import User
from relationships.models.dating import Dating

from relationships.utils.hashids import get_encoded_comment_hashid

from django.dispatch import receiver
from django.db.models.signals import post_save
from notifications import notify


class Comment(models.Model):
    hash_id = models.CharField(max_length=16, unique=True, blank=True, null=True)

    user = models.ForeignKey(User)
    dating = models.ForeignKey(Dating)

    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("dating-detail", kwargs={'slug': self.dating.hash_id}) + "#" + self.hash_id


@receiver(post_save, sender=Comment)
def _send_notifications(sender, instance, created, **kwargs):
    if created:
        instance.hash_id = get_encoded_comment_hashid(instance.id)
        instance.save()

        if instance.user.userprofile.is_boy:
            partner = instance.dating.girl
        else:
            partner = instance.dating.boy

        notify.send(instance.user, recipient=partner,
                    action_object=instance, verb="created",
                    description=instance.content)

snussum/relationships/models/comments.py
from django.db import models

from django.contrib.auth.models import User
from relationships.models.dating import Dating


class Comment(models.Model):
    user = models.ForeignKey(User)
    dating = models.ForeignKey(Dating)

    content = models.TextField()
    
    created_at = models.DateTimeField(auto_now_add=True)

snussum/snussum/views.py
from django.views.generic.base import TemplateView


class Home(TemplateView):
    template_name = "home.html"


class Dashboard(TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['dating_matched_today'] = self.request.user.userprofile.dating_matched_today()
        context['datings_matched_recently'] = self.request.user.userprofile.datings_matched_recently_except_today()
        return context

snussum/snussum/views/dashboard.py
from django.views.generic.base import TemplateView

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from users.decorators import university_verified_required, profile_verifed_required


class Dashboard(TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['dating_matched_today'] = self.request.user.userprofile.dating_matched_today()
        context['datings_matched_recently'] = self.request.user.userprofile.datings_matched_recently_except_today()
        return context

    @method_decorator(login_required)
    @method_decorator(university_verified_required)
    @method_decorator(profile_verifed_required)
    def dispatch(self, *args, **kwargs):
        return super(Dashboard, self).dispatch(*args, **kwargs)

snussum/snussum/views/home.py
from django.views.generic.base import TemplateView

from relationships.models.self_dating import SelfDating


class Home(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['self_datings'] = SelfDating.objects.order_by('-ends_at')[:3]
        return context


class About(TemplateView):
    template_name = "about.html"


class Browser(TemplateView):
    template_name = "browser.html"

snussum/snussum/views/rules.py
from django.views.generic.base import TemplateView


class Privacy(TemplateView):
    template_name = "rules/privacy.html"


class Service(TemplateView):
    template_name = "rules/service.html"

snussum/snussum/templates/_partials/_analytics.html
{# Google Analytics #}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61051678-2', 'auto');
  ga('require', 'displayfeatures');
  ga('require', 'linkid', 'linkid.js');
  ga('send', 'pageview');
</script>

{# Naver Analytics #}
<script type="text/javascript" src="https://wcs.naver.net/wcslog.js"></script>
<script type="text/javascript">
if(!wcs_add) var wcs_add = {};
wcs_add["wa"] = "103db6a6dc7a710";
wcs_do();
</script>

snussum/snussum/templates/_partials/_comments.html
<!--
  ____  _   _ _   _ ____ ____  _   _ __  __   ____ ___  __  __ 
 / ___|| \ | | | | / ___/ ___|| | | |  \/  | / ___/ _ \|  \/  |
 \___ \|  \| | | | \___ \___ \| | | | |\/| || |  | | | | |\/| |
  ___) | |\  | |_| |___) |__) | |_| | |  | || |__| |_| | |  | |
 |____/|_| \_|\___/|____/____/ \___/|_|  |_(_)____\___/|_|  |_|
                                                               
 썸타는 서울대, 스누썸 ( https://snussum.com )
 서울대학생의, 서울대학생에 의한, 서울대학생을 위한 소개팅
-->

snussum/snussum/templates/_partials/_contact.html
{% load staticfiles %}

<section id="contact">
  <section id="snussum-contact" class="container animated bounceInRight">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-8">
        <div class="panel">
          <div class="panel-body">
            <p class="text-center"><strong>관리자한테 문자보내기</strong></p>
            <p class="small">
              안녕하세요. 썸타는 서울대, 스누썸 개발자 "썸날"입니다. 지속적으로 학우 여러분들에게 더 나은 스누썸 서비스를 제공하기 위해서 적극적으로 학우 여러분들의 의견을 받고자 합니다.
            </p>
            <div class="form-group">
              <textarea name="" id="contact_content" class="form-control" placeholder="스누썸에 대한 문의사항이나 피드백을 남겨주세요. 학우 여러분이 남겨주신 소중한 피드백은 서비스 개발에 큰 도움이 됩니다." rows="5"></textarea>
            </div>

            <div class="form-group">
              <span class="small success"><i class="fa fa-check"></i> 답장이 필요한 문의의 경우 연락처를 남겨주시면 제가 직접 확인 후 빠르게 연락드릴 수 있도록 하겠습니다. 감사합니다.</span>
              <input type="tel" value="" name="" id="contact_contact" class="form-control" placeholder="(선택) 010-0000-0000"/>
            </div>

            <button type="submit" class="text-center btn-snussum-darkgrey">
              <i class="fa fa-sign-in"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;관리자한테 문자 보내기
            </button>

            <a href="http://goto.kakao.com/@snussum" target="_blank" class="text-center social-login social-login-kakao">
              <i class="fa fa-comment"></i>
              카카오톡으로 바로 문의하기
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <img class="" src="{% static "img/profile/transparent/boy.png" %}" alt=""/>
</section>

snussum/snussum/templates/_partials/_footer.html
<footer id="footer" class="footer">
  <div class="container">
    <div class="row">
      <section id="legal" class="col-md-8 col-sm-12">
        <ul>
          <li><a href="{% url "rule-service" %}">서비스 이용약관</a></li>
          <li><a href="{% url "rule-privacy" %}">개인정보 보호정책</a></li>
        </ul>

        <p>
          매칭 이후 서비스 이용자간의 만남에 대한 책임은 전적으로 해당 사용자에 있습니다만<br />
          커뮤니케이션에 대한 문제가 발생한다면, 스누썸은 책임감을 갖고 돕습니다.
        </p>
      </section>

      <section class="col-md-4 hidden-xs hidden-sm">
        <h1 class="jua">썸타는 서울대 :: 스누썸</h1>
      </section>
    </div>
  </div>
</footer>

snussum/snussum/templates/_partials/_google-analytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61051678-2', 'auto');
  ga('require', 'displayfeatures');
  ga('require', 'linkid', 'linkid.js');
  ga('send', 'pageview');
</script>

snussum/snussum/templates/_partials/_header.html
<header id="header" class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a href="{% url "home" %}" class="navbar-brand jua">썸타는 서울대학교 :: 스누썸</a>
      <button type="button" class="navbar-toggle"
        data-toggle="collapse"
        data-target=".navbar-collapse"
        >
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <ul class="nav navbar-nav navbar-left collapse navbar-collapse">
      <li><a href="{% url "about" %}">서비스 소개</a></li>
      <li><a href="{% url "dashboard" %}">오늘의 매칭</a></li>
      <li><a href="{% url "self-dating-list" %}">셀프소개팅</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right collapse navbar-collapse">
      {% if user.is_authenticated %}
        <li class="hidden-md hidden-lg">
        <a href="{% url "users:notification" %}">
            <i class="fa fa-bell"></i>
            <span class="label label-default">{% if user.notifications.unread %}{{ user.notifications.unread.count }}{% endif %}</span>
          </a>
        </li>
        <li class="dropdown hidden-xs hidden-sm">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <i class="fa fa-bell"></i>
            <span class="label label-default">{% if user.notifications.unread %}{{ user.notifications.unread.count }}{% endif %}</span>
          </a>
          <ul class="dropdown-menu notifications" role="notifications">
            {% for notification in user.notifications.unread|slice:"3" %}
              {% include "users/_notifications/_notification.html" with notification=notification %}
            {% endfor %}
            <li class="notification-center text-center"><a href="{% url 'users:notification' %}">알람 전체보기</a></li>
          </ul>
        </li>
        <li><a href="{% url "users:profile" %}">마이페이지</a></li>
        <li><a href="{% url "users:logout" %}">로그아웃</a></li>
      {% else %}
        <li><a href="{% url "users:login" %}" class="btn-login">로그인</a></li>
        <li><a href="{% url "users:signup" %}" class="btn-signup">회원가입하고 썸타기</a></li>
      {% endif %}
    </ul>
  </div>
</header>

snussum/snussum/templates/_partials/_loading.html
{% load staticfiles %}

<section id="loading" class="hide">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-4 col-md-offset-4 text-center">
        <div id="loading-content">
          <img class="fa-pulse" src="{% static "img/profile/transparent/boy.png" %}" alt=""/>
          <p>잠시만 기다려주세요...</p>
        </div>
      </div>
    </div>
  </div>
</section>

snussum/snussum/templates/_partials/_security.html
<script type="text/javascript" charset="utf-8">
{# Disable Right Click #}
$(document).on("contextmenu",function(e){
    $.notify({message: "오른쪽 마우스 클릭은 보안상의 이유로 제한되어 있습니다. \
      더 나은 서비스를 위해서 노력하겠습니다. 감사합니다."}, {type: 'danger'});
    return false;
});
</script>